version: '3'
services:
  jenkins:
    build: .  
    user: root
    ports:
      - "8080:8080"  
    volumes:
      - jenkins_home:/var/jenkins_home 
      - /var/run/docker.sock:/var/run/docker.sock #possibly dont need this line
      - .:/workspace  

volumes:
  jenkins_home:
